name: "Publish to Docker"
description: "Pushes built artifacts to Docker"

inputs:
  registry_username:
    description: “Username for image registry”
    required: true
  registry_password:
    description: “Password for image registry”
    required: true
  image_name:
    description: “Name of the image to push”
    required: true
  image_tag:
    description: “Tag of the image to push”
    required: true

runs:
  using: "composite"
  steps:
      - uses: docker/setup-buildx-action@v2

      - uses: docker/login-action@v2
        with:
          username: ${{inputs.registry_username}}
          password: ${{inputs.registry_password}}

      - uses: docker/build-push-action@v2
        with:
          context: .
          file: ./dockerfiles/Dockerfile
          push: true
          tags: ${{inputs.registry_username}}/${{inputs.image_name}}:${{inputs.image_tag}}